// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const POSTGRES_URL =
  process.env["POSTGRES_URL"] ||
  "postgresql://postgres:password@localhost:5432/mydb";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: POSTGRES_URL,
  },
});
